### ISSUE TITLE
detail page is broken

### ISSUE THREAD

**Issue by breaker92** [FACT-Finder-Web-Components/shopware6-plugin#33]
detail page is broken, cause of the the following lines:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/7db5189b4d45aefcbba5ef81be81bbd9bb7b872f/src/Resources/views/storefront/page/product-detail/tabs.html.twig#L7-L9
with error:
```
A hash key must be followed by a colon (:). Unexpected token "punctuation" of value "}" ("punctuation" expected with value ":").
{% sw_include '@Parent/storefront/components/factfinder/recommendation.html.twig' with { product_number } %}
```
If you pase variables to a twig include these variables must have keys, so instead of:
```twig
{% sw_include '@Parent/storefront/components/factfinder/recommendation.html.twig' with { product_number } %}
```
use

```twig
{% sw_include '@Parent/storefront/components/factfinder/recommendation.html.twig' with { product_number: product_number } %}
```

or use 
```twig
{% sw_include '@Parent/storefront/components/factfinder/recommendation.html.twig'  %}
```
cause the scope is inherited to the included file

**Comment by a-laurowski** [comment]
Hi @breaker92 
Thanks for reporting that. I still wonder how it worked on my local without throwing an parsing error using development template.
The PR is ready

**Comment by a-laurowski** [comment]
@breaker92 
Just to make sure, what version of twig do you have installed?
Shopware6.4 : `"twig/twig": "3.3.0" - no error
Shopware 6.3: `"twig/twig": "2.12.3" ` - error orccurs

**Comment by breaker92** [comment]
Well, your plugin is currently marked as compatible to Shopware 6.3. 
We're on the update process to 6.4 but not finished yet.

Maybe it would help if you tag Versions, so we're able to require the correct version in each case?

**Comment by a-laurowski** [comment]
@breaker92 
I'm not trying to prove my point, just trying to get know what was the reason it worked for me, nothing more :) Fix will be merged, for sure. Even if skipping key works with Twig 3, it could be a unwanted side effect from authors because i didn't find any information saying that this syntax is correct.

The versions will be tagged after we officially released the module which we planned for the end of the June. There is still an ongoing topic if we should drop the 6.3 support or keep the backward compatibility with more effort.

**Comment by a-laurowski** [comment]
I'm closing the issue since the fix is merged. If you find any other issues, don't hesitate to report them.
