### ISSUE TITLE
FactFinder Plugin affects mobile view port

### ISSUE THREAD

**Issue by breaker92** [FACT-Finder-Web-Components/shopware6-plugin#54]
If the plugin is installed it affects the mobile viewport.
It seems to set the wrong width for the body-tag due to a bracket error.
If I remove the following scss lines the problem does not occur anymore.
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/93b369aee8f5fd8b42ca064e15b0c5bbf91a41c7/src/Resources/app/storefront/src/scss/_asn.scss#L53-L71
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/93b369aee8f5fd8b42ca064e15b0c5bbf91a41c7/src/Resources/app/storefront/src/scss/_asn.scss#L83-L85

It is comprehensible in this demo installation, http://45.11.16.43/, here only the FactFinder plugin is installed.
![image](https://user-images.githubusercontent.com/9318890/129865704-283481e5-e154-414e-a76a-84d66a0b3c4f.png)

**Comment by a-laurowski** [comment]
Hi @breaker92 and thanks for reporting, we will check this out.

**Comment by a-laurowski** [comment]
Hi @breaker92 and thanks for reporting, we will look into that

**Comment by a-laurowski** [comment]
Hi @breaker92  it looks like this is caused by the @at-root rule. I don't know what was the reason standing behind adding it, but since they are nested in ff-asn selector, it should be valid.
I removed these rules locally, build the output all.css file and override the all.css in your environment using Overrides and looks its working.

Without Overrides
![image](https://user-images.githubusercontent.com/4511883/130046404-361fa431-6376-4869-bab8-4111e72c116b.png)

With Overrides:
![image](https://user-images.githubusercontent.com/4511883/130046460-9c0cef5b-4cf5-4c1b-86ce-0aef85a4da6a.png)
